package program;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Arrays;

public class OCR {
	ArrayList<BufferedImage> comma = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> zero = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> one = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> two = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> three = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> four = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> five = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> six = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> seven = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> eight = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> nine = new ArrayList<BufferedImage>();

	ArrayList<BufferedImage> hyphen = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> a = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> b = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> c = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> d = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> e = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> f = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> g = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> h = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> i = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> j = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> k = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> l = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> m = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> n = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> o = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> p = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> q = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> r = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> s = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> t = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> u = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> v = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> w = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> x = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> y = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> z = new ArrayList<BufferedImage>();

	ArrayList<BufferedImage> fe = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> fo = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> fy = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> rd = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> re = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> rg = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> rh = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> ro = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> rs = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> ry = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> rys = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> te = new ArrayList<BufferedImage>();
	ArrayList<BufferedImage> to = new ArrayList<BufferedImage>();

	String[]possibleNames = {"Carrot Seeds", 
			"Carrots", 
			"Letter of Transfer", 
			"Delivery: Blueprints", 
			"Delivery: Artistic Manuscripts", 
			"Delivery: Geomantic Surveys", 
			"Delivery: Mortar", 
			"Delivery: Crates", 
			"Delivery: Barrels", 
			"Delivery: Heavy Fur", 
			"Delivery: \"The Package\"", 
			"Delivery: Patrol Route", 
			"Delivery: Geoff the Brigand's All-Natural Enriched Moonshine", 
			"Delivery: Sack of Kittens", 
			"Delivery: Beehives", 
			"Delivery: Old Clothes", 
			"Delivery: Farmyard Tools", 
			"Delivery: Pile of Manure", 
			"Delivery: Assassination Order", 
			"Delivery: Casualty Report", 
			"Delivery: Regimental Rings", 
			"Delivery: Medical Supplies", 
			"Delivery: Sensitive Barrels", 
			"Royal \"Horse\" Token", 
			"Rough Logs", 
			"Rough Stone", 
			"Scraps of Hide", 
			"Trash", 
			"Carrot Soup", 
			"Beginner's Shield", 
			"Beginner's Mercenary Hood", 
			"Beginner's Mercenary Jacket", 
			"Beginner's Mercenary Shoes", 
			"albion.ITEMS_UNIQUE_WEAPONMASTER_HEAD_PROTOTYPE", 
			"albion.ITEMS_UNIQUE_WEAPONMASTER_ARMOR_PROTOTYPE", 
			"albion.ITEMS_UNIQUE_WEAPONMASTER_SHOES_PROTOTYPE", 
			"Beginner's Pickaxe", 
			"Beginner's Stone Hammer", 
			"Beginner's Axe", 
			"Beginner's Sickle", 
			"Beginner's Skinning Knife", 
			"Beginner's Broadsword", 
			"Haystack", 
			"Haystack and cart", 
			"Tree stump with pumpkins", 
			"Fire bowl", 
			"Fire bowl with pedestal", 
			"Small arcane stone sigil", 
			"Arcane stone sigil", 
			"Small nature stone sigil", 
			"Nature stone sigil", 
			"Scholar statue", 
			"Broken scholar statue", 
			"Hunting sculpture", 
			"Hunter statue", 
			"Book sculpture", 
			"Magician statue", 
			"Small sword sculpture", 
			"Sword sculpture", 
			"Sword and shield sculpture", 
			"Warrior statue", 
			"Small valorous stone sigil", 
			"Valorous stone sigil", 
			"Stone well", 
			"Autumn tree", 
			"Summer tree", 
			"Spring tree", 
			"Small fruit tree", 
			"Fruit tree", 
			"Bunting portal", 
			"Wooden watchtower", 
			"Wooden sign", 
			"Wooden entrance", 
			"Wooden gate", 
			"Clothes line", 
			"Fish line", 
			"Flower vase", 
			"Simple lantern", 
			"Corner lantern", 
			"Candelabra", 
			"Barrel with candle", 
			"Bean Seed", 
			"Arcane Agaric Seed", 
			"Beans", 
			"Arcane Agaric", 
			"Birch Logs", 
			"Limestone", 
			"Copper Ore", 
			"Rugged Hide", 
			"Cotton", 
			"Birch Planks", 
			"Limestone Block", 
			"Copper Bar", 
			"Stiff Leather", 
			"Simple Cloth", 
			"Trash", 
			"Minor Healing Potion", 
			"Minor Energy Potion", 
			"Bean Salad", 
			"albion.ITEMS_UNIQUE_WEAPONMASTER_POTION_PROTOTYPE", 
			"albion.ITEMS_UNIQUE_WEAPONMASTER_IDLE_PROTOTYPE", 
			"Novice's Shield", 
			"Novice's Tome of Spells", 
			"Novice's Cape", 
			"Novice's Bag", 
			"Recruiters Cape", 
			"Explorer's Hat", 
			"Explorer's Armor", 
			"Explorer's Boots", 
			"Adventurer's Helmet", 
			"Adventurer's Jacket", 
			"Adventurer's Shoes", 
			"Novice's Soldier Helmet", 
			"Novice's Soldier Armor", 
			"Novice's Soldier Boots", 
			"Novice's Mercenary Hood", 
			"Novice's Mercenary Jacket", 
			"Novice's Mercenary Shoes", 
			"Novice's Scholar Cowl", 
			"Novice's Scholar Robe", 
			"Novice's Scholar Sandals", 
			"Novice's Pickaxe", 
			"Novice's Stone Hammer", 
			"Novice's Axe", 
			"Novice's Sickle", 
			"Novice's Skinning Knife", 
			"Novice's Demolition Hammer", 
			"Novice's Bow", 
			"Novice's Fire Staff", 
			"Novice's Broadsword", 
			"Novice's Mule", 
			"Guild Banner on fabric", 
			"Guild Banner on shield", 
			"Novice's Bed", 
			"Novice's Chest", 
			"Novice's Table", 
			"Adventurer's Handbook", 
			"Novice Mercenary's Trophy", 
			"Stuffed Fox Head", 
			"Novice Lumberjack's Journal (Partially Full)", 
			"Novice Stonecutter's Journal (Partially Full)", 
			"Novice Prospector's Journal (Partially Full)", 
			"Novice Cropper's Journal (Partially Full)", 
			"Novice Gamekeeper's Journal (Partially Full)", 
			"Novice Blacksmith's Journal (Partially Full)", 
			"Novice Fletcher's Journal (Partially Full)", 
			"Novice Imbuer's Journal (Partially Full)", 
			"Novice Tinker's Journal (Partially Full)", 
			"Novice Mercenary's Journal (Partially Full)", 
			"Novice's Generalist Trophy Journal (Partially Full)", 
			"Novice Mercenary's Trophy Journal (Partially Full)", 
			"Novice Gamekeeper's Trophy Journal (Partially Full)", 
			"Wheat Seeds", 
			"Brightleaf Comfrey Seed", 
			"Journeyman's Ox Calf", 
			"Journeyman's Foal", 
			"Baby Chickens", 
			"Journeyman's Horse", 
			"Journeyman's Ox", 
			"Chicken", 
			"Sheaf of Wheat", 
			"Brightleaf Comfrey", 
			"Hen Eggs", 
			"Raw Chicken", 
			"Flour", 
			"Chestnut Logs", 
			"Sandstone", 
			"Tin Ore", 
			"Thin Hide", 
			"Flax", 
			"Chestnut Planks", 
			"Sandstone Block", 
			"Bronze Bar", 
			"Thick Leather", 
			"Neat Cloth", 
			"Trash", 
			"Explorer's Anchor", 
			"Minor Gigantify Potion", 
			"Minor Resistance Potion", 
			"Minor Sticky Potion", 
			"Wheat Soup", 
			"Chicken Pie", 
			"Chicken Omelette", 
			"Royal Blue Fireworks", 
			"Royal Green Fireworks", 
			"Royal Red Fireworks", 
			"Royal Yellow Fireworks", 
			"Journeyman's Shield", 
			"Journeyman's Tome of Spells", 
			"Journeyman's Torch", 
			"Journeyman's Cape", 
			"Journeyman's Bag", 
			"Uncle Frost's Hat", 
			"Legendary Explorer's Cloak", 
			"Legendary Explorer's Hat", 
			"Legendary Explorer's Armor", 
			"Legendary Explorer's Boots", 
			"Legendary Adventurer's Cloak", 
			"Legendary Adventurer's Hat", 
			"Legendary Adventurer's Armor", 
			"Legendary Adventurer's Boots", 
			"Journeyman's Soldier Helmet", 
			"Journeyman's Soldier Armor", 
			"Journeyman's Soldier Boots", 
			"Journeyman's Mercenary Hood", 
			"Journeyman's Mercenary Jacket", 
			"Journeyman's Mercenary Shoes", 
			"Journeyman's Scholar Cowl", 
			"Journeyman's Scholar Robe", 
			"Journeyman's Scholar Sandals", 
			"Journeyman's Pickaxe", 
			"Journeyman's Stone Hammer", 
			"Journeyman's Axe", 
			"Journeyman's Sickle", 
			"Journeyman's Skinning Knife", 
			"Journeyman's Demolition Hammer", 
			"Journeyman's Bow", 
			"Journeyman's Crossbow", 
			"Journeyman's Cursed Staff", 
			"Journeyman's Fire Staff", 
			"Journeyman's Frost Staff", 
			"Journeyman's Arcane Staff", 
			"Journeyman's Holy Staff", 
			"Journeyman's Nature Staff", 
			"Journeyman's Dagger", 
			"Journeyman's Spear", 
			"Journeyman's Battleaxe", 
			"Journeyman's Broadsword", 
			"Journeyman's Quarterstaff", 
			"Journeyman's Hammer", 
			"Journeyman's Mace", 
			"Journeyman's Riding Horse", 
			"Journeyman's Transport Ox", 
			"Recruiter's Horse", 
			"Recruiter's Donkey", 
			"Legendary Explorer's Horse", 
			"Legendary Explorer's Ox", 
			"Epic Explorer's Giant Stag", 
			"Legendary Adventurer's Horse", 
			"Legendary Adventurer's Cart", 
			"Guild Banner on fabric", 
			"Guild Banner on shield", 
			"Journeyman's Bed", 
			"Journeyman's Chest", 
			"Journeyman's Table", 
			"Explorer's Looking Glass", 
			"Founder's Certificate", 
			"Founder's Statue", 
			"Magical Tome", 
			"Journeyman Mercenary's Trophy", 
			"Stuffed Wolf Head", 
			"Journeyman Lumberjack's Journal (Partially Full)", 
			"Journeyman Stonecutter's Journal (Partially Full)", 
			"Journeyman Prospector's Journal (Partially Full)", 
			"Journeyman Cropper's Journal (Partially Full)", 
			"Journeyman Gamekeeper's Journal (Partially Full)", 
			"Journeyman Blacksmith's Journal (Partially Full)", 
			"Journeyman Fletcher's Journal (Partially Full)", 
			"Journeyman Imbuer's Journal (Partially Full)", 
			"Journeyman Tinker's Journal (Partially Full)", 
			"Journeyman Mercenary's Journal (Partially Full)", 
			"Journeyman's Generalist Trophy Journal (Partially Full)", 
			"Journeyman Mercenary's Trophy Journal (Partially Full)", 
			"Journeyman Gamekeeper's Trophy Journal (Partially Full)", 

			"Journeyman Lumberjack's Journal (empty)", 
			"Journeyman Stonecutter's Journal (empty)", 
			"Journeyman Prospector's Journal (empty)", 
			"Journeyman Cropper's Journal (empty)", 
			"Journeyman Gamekeeper's Journal (empty)", 
			"Journeyman Blacksmith's Journal (empty)", 
			"Journeyman Fletcher's Journal (empty)", 
			"Journeyman Imbuer's Journal (empty)", 
			"Journeyman Tinker's Journal (empty)", 
			"Journeyman Mercenary's Journal (empty)", 
			"Journeyman's Generalist Trophy Journal (empty)", 
			"Journeyman Mercenary's Trophy Journal (empty)", 
			"Journeyman Gamekeeper's Trophy Journal (empty)", 

			"Turnip Seed", 
			"Crenellated Burdock Seed", 
			"Adept's Ox Calf", 
			"Adept's Foal", 
			"Adept's Fawn", 
			"Kid", 
			"Adept's Horse", 
			"Adept's Ox", 
			"Adept's Tame Giant Stag", 
			"Goat", 
			"Turnips", 
			"Crenellated Burdock", 
			"Goat's Milk", 
			"Adept's Royal Sigil", 
			"Raw Goat", 
			"Goat's Butter", 
			"Bread", 
			"Pine Logs", 
			"Uncommon Pine Logs", 
			"Rare Pine Logs", 
			"Exceptional Pine Logs", 
			"Travertine", 
			"Iron Ore", 
			"Uncommon Iron Ore", 
			"Rare Iron Ore", 
			"Exceptional Iron Ore", 
			"Medium Hide", 
			"Uncommon Medium Hide", 
			"Rare Medium Hide", 
			"Exceptional Medium Hide", 
			"Hemp", 
			"Uncommon Hemp", 
			"Rare Hemp", 
			"Exceptional Hemp", 
			"Pine Planks", 
			"Uncommon Pine Planks", 
			"Rare Pine Planks", 
			"Exceptional Pine Planks", 
			"Travertine Block", 
			"Steel Bar", 
			"Uncommon Steel Bar", 
			"Rare Steel Bar", 
			"Exceptional Steel Bar", 
			"Worked Leather", 
			"Uncommon Worked Leather", 
			"Rare Worked Leather", 
			"Exceptional Worked Leather", 
			"Fine Cloth", 
			"Uncommon Fine Cloth", 
			"Rare Fine Cloth", 
			"Exceptional Fine Cloth", 
			"Adept's Occult Orb", 
			"Adept's Demonic Arrowheads", 
			"Adept's Carved bone", 
			"Adept's Demonic Blade", 
			"Adept's Reinforced Morgana Pole", 
			"Adept's Alluring Bolts", 
			"Adept's Bloodforged Catalyst", 
			"Adept's Keeper Axeheads", 
			"Adept's Hellish Bolts", 
			"Adept's Hellish Hammer Heads", 
			"Adept's Cursed Blades", 
			"Adept's Ghastly Blades", 
			"Adept's Possessed Catalyst", 
			"Adept's Burning Orb", 
			"Adept's Morgana Halberd Head", 
			"Adept's Ancient Hammer Head", 
			"Adept's Infernal Harpoon Tip", 
			"Adept's Possessed Scroll", 
			"Adept's Infernal Scroll", 
			"Adept's Ghastly Scroll", 
			"Adept's Cursed Frozen Crystal", 
			"Adept's Icicle Orb", 
			"Adept's Unholy Scroll", 
			"Adept's Black Leather", 
			"Adept's Ghastly Arrows", 
			"Adept's Imbued Mace Head", 
			"Adept's Symbol of Blight", 
			"Adept's Preserved Log", 
			"Adept's Engraved Log", 
			"Adept's Lost Crossbow Mechanism", 
			"Adept's Preserved Rocks", 
			"Adept's Cursed Jawbone", 
			"Adept's Cursed Barbs", 
			"Adept's Hellish Sicklehead Pair", 
			"Adept's Lost Arcane Crystal", 
			"Adept's Lost Cursed Crystal", 
			"Adept's Wildfire Orb", 
			"Adept's Hoarfrost Orb", 
			"Adept's Infernal Mace Head", 
			"Adept's Druidic Inscriptions", 
			"Adept's Hardened Debole", 
			"Adept's Runed Rock", 
			"Adept's Bloodforged Blade", 
			"Adept's Keeper Spearhead", 
			"Adept's Hellish Sicklehead", 
			"Adept's Ancient Shield Core", 
			"Adept's Infernal Shield Core", 
			"Adept's Bloodforged Spikes", 
			"Adept's Alluring Crystal", 
			"Adept's Demonic Jawbone", 
			"Adept's Inscribed Stone", 
			"Adept's Runed Horn", 
			"Adept's Hellish Handle", 
			"Adept's Ghastly Candle", 
			"Adept's Ancient Padding", 
			"Adept's Ancient Chain Rings", 
			"Adept's Ancient Bindings", 
			"Adept's Demonic Scraps", 
			"Adept's Demonic Plates", 
			"Adept's Demonic Filling", 
			"Adept's Carved Skull Padding", 
			"Adept's Preserved Animal Fur", 
			"Adept's Inscribed Bindings", 
			"Adept's Imbued Visor", 
			"Adept's Imbued Leather Folds", 
			"Adept's Imbued Soles", 
			"Adept's Demonhide Padding", 
			"Adept's Demonhide Leather", 
			"Adept's Demonhide Bindings", 
			"Adept's Ghastly Visor", 
			"Adept's Ghastly Leather", 
			"Adept's Ghastly Bindings", 
			"Adept's Druidic Preserved Beak", 
			"Adept's Druidic Feathers", 
			"Adept's Druidic Bindings", 
			"Adept's Infernal Cloth Visor", 
			"Adept's Infernal Cloth Folds", 
			"Adept's Infernal Cloth Bindings", 
			"Adept's Alluring Padding", 
			"Adept's Alluring Amulet", 
			"Adept's Alluring Bindings", 
			"Adept's Essence", 
			"Adept's Rune", 
			"Adept's Soul", 
			"Adept's Relic", 
			"Trash", 
			"Healing Potion", 
			"Energy Potion", 
			"Minor Poison Potion", 
			"Turnip Salad", 
			"Goat Stew", 
			"Goat Sandwich", 
			"Snowball", 
			"Adept's Shield", 
			"Adept's Sarcophagus", 
			"Adept's Caitiff Shield", 
			"Adept's Facebreaker", 
			"Adept's Tome of Spells", 
			"Adept's Eye of Secrets", 
			"Adept's Muisak", 
			"Adept's Taproot", 
			"Adept's Torch", 
			"Adept's Mistcaller", 
			"Adept's Leering Cane", 
			"Adept's Cryptcandle", 
			"Adept's Cape", 
			"Adept's Bag", 
			"Adept's Soldier Helmet", 
			"Adept's Soldier Armor", 
			"Adept's Soldier Boots", 
			"Adept's Knight Helmet", 
			"Adept's Knight Armor", 
			"Adept's Knight Boots", 
			"Adept's Guardian Helmet", 
			"Adept's Guardian Armor", 
			"Adept's Guardian Boots", 
			"Adept's Graveguard Helmet", 
			"Adept's Graveguard Armor", 
			"Adept's Graveguard Boots", 
			"Adept's Demon Helmet", 
			"Adept's Demon Armor", 
			"Adept's Demon Boots", 
			"Adept's Judicator Helmet", 
			"Adept's Judicator Armor", 
			"Adept's Judicator Boots", 
			"Adept's Mercenary Hood", 
			"Adept's Mercenary Jacket", 
			"Adept's Mercenary Shoes", 
			"Adept's Hunter Hood", 
			"Adept's Hunter Jacket", 
			"Adept's Hunter Shoes", 
			"Adept's Assassin Hood", 
			"Adept's Assassin Jacket", 
			"Adept's Assassin Shoes", 
			"Adept's Stalker Hood", 
			"Adept's Stalker Jacket", 
			"Adept's Stalker Shoes", 
			"Adept's Hellion Hood", 
			"Adept's Hellion Jacket", 
			"Adept's Hellion Shoes", 
			"Adept's Specter Hood", 
			"Adept's Specter Jacket", 
			"Adept's Specter Shoes", 
			"Adept's Scholar Cowl", 
			"Adept's Scholar Robe", 
			"Adept's Scholar Sandals", 
			"Adept's Cleric Cowl", 
			"Adept's Cleric Robe", 
			"Adept's Cleric Sandals", 
			"Adept's Mage Cowl", 
			"Adept's Mage Robe", 
			"Adept's Mage Sandals", 
			"Adept's Druid Cowl", 
			"Adept's Druid Robe", 
			"Adept's Druid Sandals", 
			"Adept's Fiend Cowl", 
			"Adept's Fiend Robe", 
			"Adept's Fiend Sandals", 
			"Adept's Cultist Cowl", 
			"Adept's Cultist Robe", 
			"Adept's Cultist Sandals", 
			"Adept's Royal Cowl", 
			"Adept's Royal Robe", 
			"Adept's Royal Sandals", 
			"Adept's Royal Hood", 
			"Adept's Royal Jacket", 
			"Adept's Royal Shoes", 
			"Adept's Royal Helmet", 
			"Adept's Royal Armor", 
			"Adept's Royal Boots", 
			"Adept's Harvester Cap", 
			"Adept's Harvester Garb", 
			"Adept's Harvester Workboots", 
			"Adept's Harvester Backpack", 
			"Adept's Skinner Cap", 
			"Adept's Skinner Garb", 
			"Adept's Skinner Workboots", 
			"Adept's Skinner Backpack", 
			"Adept's Miner Cap", 
			"Adept's Miner Garb", 
			"Adept's Miner Workboots", 
			"Adept's Miner Backpack", 
			"Adept's Quarrier Cap", 
			"Adept's Quarrier Garb", 
			"Adept's Quarrier Workboots", 
			"Adept's Quarrier Backpack", 
			"Adept's Lumberjack Cap", 
			"Adept's Lumberjack Garb", 
			"Adept's Lumberjack Workboots", 
			"Adept's Lumberjack Backpack", 
			"Adept's Pickaxe", 
			"Adept's Stone Hammer", 
			"Adept's Axe", 
			"Adept's Sickle", 
			"Adept's Skinning Knife", 
			"Adept's Demolition Hammer", 
			"Adept's Bow", 
			"Adept's Warbow", 
			"Adept's Longbow", 
			"Adept's Whispering Bow", 
			"Adept's Wailing Bow", 
			"Adept's Bow of Badon", 
			"Adept's Crossbow", 
			"Adept's Heavy Crossbow", 
			"Adept's Light Crossbow", 
			"Adept's Weeping Repeater", 
			"Adept's Boltcasters", 
			"Adept's Siegebow", 
			"Adept's Cursed Staff", 
			"Adept's Great Cursed Staff", 
			"Adept's Demonic Staff", 
			"Adept's Lifecurse Staff", 
			"Adept's Cursed Skull", 
			"Adept's Damnation Staff", 
			"Adept's Fire Staff", 
			"Adept's Great Fire Staff", 
			"Adept's Infernal Staff", 
			"Adept's Wildfire Staff", 
			"Adept's Brimstone Staff", 
			"Adept's Blazing Staff", 
			"Adept's Frost Staff", 
			"Adept's Great Frost Staff", 
			"Adept's Glacial Staff", 
			"Adept's Hoarfrost Staff", 
			"Adept's Icicle Staff", 
			"Adept's Permafrost Prism", 
			"Adept's Arcane Staff", 
			"Adept's Great Arcane Staff", 
			"Adept's Enigmatic Staff", 
			"Adept's Witchwork Staff", 
			"Adept's Occult Staff", 
			"Adept's Eye of Secrets", 
			"Adept's Holy Staff", 
			"Adept's Great Holy Staff", 
			"Adept's Divine Staff", 
			"Adept's Lifetouch Staff", 
			"Adept's Fallen Staff", 
			"Adept's Redemption Staff", 
			"Adept's Nature Staff", 
			"Adept's Great Nature Staff", 
			"Adept's Wild Staff", 
			"Adept's Druidic Staff", 
			"Adept's Blight Staff", 
			"Adept's Rampant Staff", 
			"Adept's Dagger", 
			"Adept's Dagger Pair", 
			"Adept's Claws", 
			"Adept's Bloodletter", 
			"Adept's Black Hands", 
			"Adept's Deathgivers", 
			"Adept's Spear", 
			"Adept's Pike", 
			"Adept's Glaive", 
			"Adept's Heron Spear", 
			"Adept's Spirithunter", 
			"Adept's Trinity Spear", 
			"Adept's Battleaxe", 
			"Adept's Greataxe", 
			"Adept's Halberd", 
			"Adept's Carrioncaller", 
			"Adept's Infernal Scythe", 
			"Adept's Bear Paws", 
			"Adept's Broadsword", 
			"Adept's Claymore", 
			"Adept's Dual Swords", 
			"Adept's Clarent Blade", 
			"Adept's Carving Sword", 
			"Adept's Galatine Pair", 
			"Adept's Quarterstaff", 
			"Adept's Iron-clad Staff", 
			"Adept's Double Bladed Staff", 
			"Adept's Black Monk Stave", 
			"Adept's Soulscythe", 
			"Adept's Staff of Balance", 
			"Adept's Hammer", 
			"Adept's Polehammer", 
			"Adept's Great Hammer", 
			"Adept's Tombhammer", 
			"Adept's Forge Hammers", 
			"Adept's Grovekeeper", 
			"Adept's Mace", 
			"Adept's Heavy Mace", 
			"Adept's Morning Star", 
			"Adept's Bedrock Mace", 
			"Adept's Incubus Mace", 
			"Adept's Camlann Mace", 
			"Adept's Riding Horse", 
			"Adept's Transport Ox", 
			"Adept's Giant Stag", 
			"Adept's Repair Kit", 
			"Guild Banner on fabric", 
			"Guild Banner on shield", 
			"Adept's Bed", 
			"Adept's Chest", 
			"Adept's Table", 
			"Keeper Symbol", 
			"Keeper Ceremonial Candle", 
			"Keeper Shrine", 
			"Keeper Campfire", 
			"Keeper Altar", 
			"Keeper Flag", 
			"Keeper Symbol of Power", 
			"Keeper Star of Power", 
			"Heretic Food Stash", 
			"Heretic Animal Cages", 
			"Heretic Weapon Rack", 
			"Heretic Training Dummy", 
			"Heretic Pallisade", 
			"Heretic Game Table", 
			"Heretic Flag", 
			"Heretic Chief's Table", 
			"Heretic Tent", 
			"Ancient Scripture", 
			"Adept Mercenary's Trophy", 
			"Stuffed Boar Head", 
			"Adept Lumberjack's Journal (Partially Full)", 
			"Adept Stonecutter's Journal (Partially Full)", 
			"Adept Prospector's Journal (Partially Full)", 
			"Adept Cropper's Journal (Partially Full)", 
			"Adept Gamekeeper's Journal (Partially Full)", 
			"Adept Blacksmith's Journal (Partially Full)", 
			"Adept Fletcher's Journal (Partially Full)", 
			"Adept Imbuer's Journal (Partially Full)", 
			"Adept Tinker's Journal (Partially Full)", 
			"Adept Mercenary's Journal (Partially Full)", 
			"Adept's Generalist Trophy Journal (Partially Full)", 
			"Adept Mercenary's Trophy Journal (Partially Full)", 
			"Adept Gamekeeper's Trophy Journal (Partially Full)", 
			"Cabbage Seed", 
			"Dragon Teasel Seed", 
			"Expert's Ox Calf", 
			"Expert's Foal", 
			"Swiftclaw Cub", 
			"Gosling", 
			"Expert's Horse", 
			"Expert's Ox", 
			"Tame Swiftclaw", 
			"Goose", 
			"Necromantic Elixir", 
			"Warhorse Saddle", 
			"Cabbage", 
			"Dragon Teasel", 
			"Goose Eggs", 
			"Expert's Royal Sigil", 
			"Raw Goose", 
			"Cedar Logs", 
			"Uncommon Cedar Logs", 
			"Rare Cedar Logs", 
			"Exceptional Cedar Logs", 
			"Granite", 
			"Titanium Ore", 
			"Uncommon Titanium Ore", 
			"Rare Titanium Ore", 
			"Exceptional Titanium Ore", 
			"Heavy Hide", 
			"Uncommon Heavy Hide", 
			"Rare Heavy Hide", 
			"Exceptional Heavy Hide", 
			"Skyflower", 
			"Uncommon Skyflower", 
			"Rare Skyflower", 
			"Exceptional Skyflower", 
			"Cedar Planks", 
			"Uncommon Cedar Planks", 
			"Rare Cedar Planks", 
			"Exceptional Cedar Planks", 
			"Granite Block", 
			"Titanium Steel Bar", 
			"Uncommon Titanium Steel Bar", 
			"Rare Titanium Steel Bar", 
			"Exceptional Titanium Steel Bar", 
			"Cured Leather", 
			"Uncommon Cured Leather", 
			"Rare Cured Leather", 
			"Exceptional Cured Leather", 
			"Ornate Cloth", 
			"Uncommon Ornate Cloth", 
			"Rare Ornate Cloth", 
			"Exceptional Ornate Cloth", 
			"Expert's Bloodforged Catalyst", 
			"Expert's Occult Orb", 
			"Expert's Demonic Arrowheads", 
			"Expert's Carved bone", 
			"Expert's Demonic Blade", 
			"Expert's Reinforced Morgana Pole", 
			"Expert's Alluring Bolts", 
			"Expert's Keeper Axeheads", 
			"Expert's Hellish Bolts", 
			"Expert's Hellish Hammer Heads", 
			"Expert's Cursed Blades", 
			"Expert's Ghastly Blades", 
			"Expert's Possessed Catalyst", 
			"Expert's Burning Orb", 
			"Expert's Morgana Halberd Head", 
			"Expert's Ancient Hammer Head", 
			"Expert's Infernal Harpoon Tip", 
			"Expert's Possessed Scroll", 
			"Expert's Infernal Scroll", 
			"Expert's Ghastly Scroll", 
			"Expert's Cursed Frozen Crystal", 
			"Expert's Icicle Orb", 
			"Expert's Unholy Scroll", 
			"Expert's Black Leather", 
			"Expert's Ghastly Arrows", 
			"Expert's Imbued Mace Head", 
			"Expert's Symbol of Blight", 
			"Expert's Preserved Log", 
			"Expert's Engraved Log", 
			"Expert's Lost Crossbow Mechanism", 
			"Expert's Preserved Rocks", 
			"Expert's Hellish Sicklehead", 
			"Expert's Cursed Jawbone", 
			"Expert's Cursed Barbs", 
			"Expert's Hellish Sicklehead Pair", 
			"Expert's Lost Arcane Crystal", 
			"Expert's Lost Cursed Crystal", 
			"Expert's Wildfire Orb", 
			"Expert's Hoarfrost Orb", 
			"Expert's Infernal Mace Head", 
			"Expert's Druidic Inscriptions", 
			"Expert's Hardened Debole", 
			"Expert's Runed Rock", 
			"Expert's Bloodforged Blade", 
			"Expert's Keeper Spearhead", 
			"Expert's Ancient Shield Core", 
			"Expert's Infernal Shield Core", 
			"Expert's Bloodforged Spikes", 
			"Expert's Alluring Crystal", 
			"Expert's Demonic Jawbone", 
			"Expert's Inscribed Stone", 
			"Expert's Runed Horn", 
			"Expert's Hellish Handle", 
			"Expert's Ghastly Candle", 
			"Expert's Ancient Padding", 
			"Expert's Ancient Chain Rings", 
			"Expert's Ancient Bindings", 
			"Expert's Demonic Scraps", 
			"Expert's Demonic Plates", 
			"Expert's Demonic Filling", 
			"Expert's Carved Skull Padding", 
			"Expert's Preserved Animal Fur", 
			"Expert's Inscribed Bindings", 
			"Expert's Imbued Visor", 
			"Expert's Imbued Leather Folds", 
			"Expert's Imbued Soles", 
			"Expert's Demonhide Padding", 
			"Expert's Demonhide Leather", 
			"Expert's Demonhide Bindings", 
			"Expert's Ghastly Visor", 
			"Expert's Ghastly Leather", 
			"Expert's Ghastly Bindings", 
			"Expert's Druidic Preserved Beak", 
			"Expert's Druidic Feathers", 
			"Expert's Druidic Bindings", 
			"Expert's Infernal Cloth Visor", 
			"Expert's Infernal Cloth Folds", 
			"Expert's Infernal Cloth Bindings", 
			"Expert's Alluring Padding", 
			"Expert's Alluring Amulet", 
			"Expert's Alluring Bindings", 
			"Expert's Essence", 
			"Expert's Rune", 
			"Expert's Soul", 
			"Expert's Relic", 
			"Trash", 
			"Gigantify Potion", 
			"Resistance Potion", 
			"Sticky Potion", 
			"Cabbage Soup", 
			"Goose Pie", 
			"Goose Omelette", 
			"Expert's Shield", 
			"Expert's Sarcophagus", 
			"Expert's Caitiff Shield", 
			"Expert's Facebreaker", 
			"Expert's Tome of Spells", 
			"Expert's Eye of Secrets", 
			"Expert's Muisak", 
			"Expert's Taproot", 
			"Expert's Torch", 
			"Expert's Mistcaller", 
			"Expert's Leering Cane", 
			"Expert's Cryptcandle", 
			"Expert's Cape", 
			"Expert's Bag", 
			"Expert's Soldier Helmet", 
			"Expert's Soldier Armor", 
			"Expert's Soldier Boots", 
			"Expert's Knight Helmet", 
			"Expert's Knight Armor", 
			"Expert's Knight Boots", 
			"Expert's Guardian Helmet", 
			"Expert's Guardian Armor", 
			"Expert's Guardian Boots", 
			"Expert's Graveguard Helmet", 
			"Expert's Graveguard Armor", 
			"Expert's Graveguard Boots", 
			"Expert's Demon Helmet", 
			"Expert's Demon Armor", 
			"Expert's Demon Boots", 
			"Expert's Judicator Helmet", 
			"Expert's Judicator Armor", 
			"Expert's Judicator Boots", 
			"Expert's Mercenary Hood", 
			"Expert's Mercenary Jacket", 
			"Expert's Mercenary Shoes", 
			"Expert's Hunter Hood", 
			"Expert's Hunter Jacket", 
			"Expert's Hunter Shoes", 
			"Expert's Assassin Hood", 
			"Expert's Assassin Jacket", 
			"Expert's Assassin Shoes", 
			"Expert's Stalker Hood", 
			"Expert's Stalker Jacket", 
			"Expert's Stalker Shoes", 
			"Expert's Hellion Hood", 
			"Expert's Hellion Jacket", 
			"Expert's Hellion Shoes", 
			"Expert's Specter Hood", 
			"Expert's Specter Jacket", 
			"Expert's Specter Shoes", 
			"Expert's Scholar Cowl", 
			"Expert's Scholar Robe", 
			"Expert's Scholar Sandals", 
			"Expert's Cleric Cowl", 
			"Expert's Cleric Robe", 
			"Expert's Cleric Sandals", 
			"Expert's Mage Cowl", 
			"Expert's Mage Robe", 
			"Expert's Mage Sandals", 
			"Expert's Druid Cowl", 
			"Expert's Druid Robe", 
			"Expert's Druid Sandals", 
			"Expert's Fiend Cowl", 
			"Expert's Fiend Robe", 
			"Expert's Fiend Sandals", 
			"Expert's Cultist Cowl", 
			"Expert's Cultist Robe", 
			"Expert's Cultist Sandals", 
			"Expert's Royal Cowl", 
			"Expert's Royal Robe", 
			"Expert's Royal Sandals", 
			"Expert's Royal Hood", 
			"Expert's Royal Jacket", 
			"Expert's Royal Shoes", 
			"Expert's Royal Helmet", 
			"Expert's Royal Armor", 
			"Expert's Royal Boots", 
			"Expert's Harvester Cap", 
			"Expert's Harvester Garb", 
			"Expert's Harvester Workboots", 
			"Expert's Harvester Backpack", 
			"Expert's Skinner Cap", 
			"Expert's Skinner Garb", 
			"Expert's Skinner Workboots", 
			"Expert's Skinner Backpack", 
			"Expert's Miner Cap", 
			"Expert's Miner Garb", 
			"Expert's Miner Workboots", 
			"Expert's Miner Backpack", 
			"Expert's Quarrier Cap", 
			"Expert's Quarrier Garb", 
			"Expert's Quarrier Workboots", 
			"Expert's Quarrier Backpack", 
			"Expert's Lumberjack Cap", 
			"Expert's Lumberjack Garb", 
			"Expert's Lumberjack Workboots", 
			"Expert's Lumberjack Backpack", 
			"Expert's Pickaxe", 
			"Expert's Stone Hammer", 
			"Expert's Axe", 
			"Expert's Sickle", 
			"Expert's Skinning Knife", 
			"Expert's Demolition Hammer", 
			"Expert's Bow", 
			"Expert's Warbow", 
			"Expert's Longbow", 
			"Expert's Whispering Bow", 
			"Expert's Wailing Bow", 
			"Expert's Bow of Badon", 
			"Expert's Crossbow", 
			"Expert's Heavy Crossbow", 
			"Expert's Light Crossbow", 
			"Expert's Weeping Repeater", 
			"Expert's Boltcasters", 
			"Expert's Siegebow", 
			"Expert's Cursed Staff", 
			"Expert's Great Cursed Staff", 
			"Expert's Demonic Staff", 
			"Expert's Lifecurse Staff", 
			"Expert's Cursed Skull", 
			"Expert's Damnation Staff", 
			"Expert's Fire Staff", 
			"Expert's Great Fire Staff", 
			"Expert's Infernal Staff", 
			"Expert's Wildfire Staff", 
			"Expert's Brimstone Staff", 
			"Expert's Blazing Staff", 
			"Expert's Frost Staff", 
			"Expert's Great Frost Staff", 
			"Expert's Glacial Staff", 
			"Expert's Hoarfrost Staff", 
			"Expert's Icicle Staff", 
			"Expert's Permafrost Prism", 
			"Expert's Arcane Staff", 
			"Expert's Great Arcane Staff", 
			"Expert's Enigmatic Staff", 
			"Expert's Witchwork Staff", 
			"Expert's Occult Staff", 
			"Expert's Eye of Secrets", 
			"Expert's Holy Staff", 
			"Expert's Great Holy Staff", 
			"Expert's Divine Staff", 
			"Expert's Lifetouch Staff", 
			"Expert's Fallen Staff", 
			"Expert's Redemption Staff", 
			"Expert's Nature Staff", 
			"Expert's Great Nature Staff", 
			"Expert's Wild Staff", 
			"Expert's Druidic Staff", 
			"Expert's Blight Staff", 
			"Expert's Rampant Staff", 
			"Expert's Dagger", 
			"Expert's Dagger Pair", 
			"Expert's Claws", 
			"Expert's Bloodletter", 
			"Expert's Black Hands", 
			"Expert's Deathgivers", 
			"Expert's Spear", 
			"Expert's Pike", 
			"Expert's Glaive", 
			"Expert's Heron Spear", 
			"Expert's Spirithunter", 
			"Expert's Trinity Spear", 
			"Expert's Battleaxe", 
			"Expert's Greataxe", 
			"Expert's Halberd", 
			"Expert's Carrioncaller", 
			"Expert's Infernal Scythe", 
			"Expert's Bear Paws", 
			"Expert's Broadsword", 
			"Expert's Claymore", 
			"Expert's Dual Swords", 
			"Expert's Clarent Blade", 
			"Expert's Carving Sword", 
			"Expert's Galatine Pair", 
			"Expert's Quarterstaff", 
			"Expert's Iron-clad Staff", 
			"Expert's Double Bladed Staff", 
			"Expert's Black Monk Stave", 
			"Expert's Soulscythe", 
			"Expert's Staff of Balance", 
			"Expert's Hammer", 
			"Expert's Polehammer", 
			"Expert's Great Hammer", 
			"Expert's Tombhammer", 
			"Expert's Forge Hammers", 
			"Expert's Grovekeeper", 
			"Expert's Mace", 
			"Expert's Heavy Mace", 
			"Expert's Morning Star", 
			"Expert's Bedrock Mace", 
			"Expert's Incubus Mace", 
			"Expert's Camlann Mace", 
			"Expert's Riding Horse", 
			"Expert's Armored Horse", 
			"Expert's Transport Ox", 
			"Bonehorse", 
			"Swiftclaw", 
			"Warhorse", 
			"Expert's Repair Kit", 
			"Guild Banner on fabric", 
			"Guild Banner on shield", 
			"Expert's Bed", 
			"Expert's Chest", 
			"Expert's Table", 
			"Flambeau (Disciples of Morgana)", 
			"Raven Standard Flambeau (Disciples of Morgana)", 
			"Pentagram (Disciples of Morgana)", 
			"Simple Brazier (Disciples of Morgana)", 
			"Reinforced Brazier (Disciples of Morgana)", 
			"Cauldron (Disciples of Morgana)", 
			"Raven Standard Shrine (Disciples of Morgana)", 
			"Siege Ballista (Disciples of Morgana)", 
			"Raven Standard (Disciples of Morgana)", 
			"Army Crate (Disciples of Morgana)", 
			"Prisoner Cage (Disciples of Morgana)", 
			"Soldier's Tent (Disciples of Morgana)", 
			"Tome of Knowledge", 
			"Expert Mercenary's Trophy", 
			"Stuffed Bear Head", 
			"Expert Lumberjack's Journal (Partially Full)", 
			"Expert Stonecutter's Journal (Partially Full)", 
			"Expert Prospector's Journal (Partially Full)", 
			"Expert Cropper's Journal (Partially Full)", 
			"Expert Gamekeeper's Journal (Partially Full)", 
			"Expert Blacksmith's Journal (Partially Full)", 
			"Expert Fletcher's Journal (Partially Full)", 
			"Expert Imbuer's Journal (Partially Full)", 
			"Expert Tinker's Journal (Partially Full)", 
			"Expert Mercenary's Journal (Partially Full)", 
			"Expert's Generalist Trophy Journal (Partially Full)", 
			"Expert Mercenary's Trophy Journal (Partially Full)", 
			"Expert Gamekeeper's Trophy Journal (Partially Full)", 
			"Potato Seeds", 
			"Elusive Foxglove Seed", 
			"Master's Ox Calf", 
			"Master's Foal", 
			"Direwolf Pup", 
			"Master's Fawn", 
			"Lamb", 
			"Master's Horse", 
			"Master's Ox", 
			"Tame Direwolf", 
			"Master's Tame Giant Stag", 
			"Sheep", 
			"Decorative Bridle", 
			"Potatoes", 
			"Elusive Foxglove", 
			"Sheep's Milk", 
			"Master's Royal Sigil", 
			"Keeper Totem", 
			"Morgana's Favour", 
			"Undead Knucklebone", 
			"Raw Mutton", 
			"Sheep's Butter", 
			"Potato Schnapps", 
			"Bloodoak Logs", 
			"Uncommon Bloodoak Logs", 
			"Rare Bloodoak Logs", 
			"Exceptional Bloodoak Logs", 
			"Slate", 
			"Runite Ore", 
			"Uncommon Runite Ore", 
			"Rare Runite Ore", 
			"Exceptional Runite Ore", 
			"Robust Hide", 
			"Uncommon Robust Hide", 
			"Rare Robust Hide", 
			"Exceptional Robust Hide", 
			"Redleaf Cotton", 
			"Uncommon Redleaf Cotton", 
			"Rare Redleaf Cotton", 
			"Exceptional Redleaf Cotton", 
			"Bloodoak Planks", 
			"Uncommon Bloodoak Planks", 
			"Rare Bloodoak Planks", 
			"Exceptional Bloodoak Planks", 
			"Slate Block", 
			"Runite Steel Bar", 
			"Uncommon Runite Steel Bar", 
			"Rare Runite Steel Bar", 
			"Exceptional Runite Steel Bar", 
			"Hardened Leather", 
			"Uncommon Hardened Leather", 
			"Rare Hardened Leather", 
			"Exceptional Hardened Leather", 
			"Lavish Cloth", 
			"Uncommon Lavish Cloth", 
			"Rare Lavish Cloth", 
			"Exceptional Lavish Cloth", 
			"Master's Bloodforged Catalyst", 
			"Master's Hellish Sicklehead", 
			"Master's Occult Orb", 
			"Master's Demonic Arrowheads", 
			"Master's Carved bone", 
			"Master's Demonic Blade", 
			"Master's Reinforced Morgana Pole", 
			"Master's Alluring Bolts", 
			"Master's Keeper Axeheads", 
			"Master's Hellish Bolts", 
			"Master's Hellish Hammer Heads", 
			"Master's Cursed Blades", 
			"Master's Ghastly Blades", 
			"Master's Possessed Catalyst", 
			"Master's Burning Orb", 
			"Master's Morgana Halberd Head", 
			"Master's Ancient Hammer Head", 
			"Master's Infernal Harpoon Tip", 
			"Master's Possessed Scroll", 
			"Master's Infernal Scroll", 
			"Master's Ghastly Scroll", 
			"Master's Cursed Frozen Crystal", 
			"Master's Icicle Orb", 
			"Master's Unholy Scroll", 
			"Master's Black Leather", 
			"Master's Ghastly Arrows", 
			"Master's Imbued Mace Head", 
			"Master's Symbol of Blight", 
			"Master's Preserved Log", 
			"Master's Engraved Log", 
			"Master's Lost Crossbow Mechanism", 
			"Master's Preserved Rocks", 
			"Master's Cursed Jawbone", 
			"Master's Cursed Barbs", 
			"Master's Hellish Sicklehead Pair", 
			"Master's Lost Arcane Crystal", 
			"Master's Lost Cursed Crystal", 
			"Master's Wildfire Orb", 
			"Master's Hoarfrost Orb", 
			"Master's Infernal Mace Head", 
			"Master's Druidic Inscriptions", 
			"Master's Hardened Debole", 
			"Master's Runed Rock", 
			"Master's Bloodforged Blade", 
			"Master's Keeper Spearhead", 
			"Master's Ancient Shield Core", 
			"Master's Infernal Shield Core", 
			"Master's Bloodforged Spikes", 
			"Master's Alluring Crystal", 
			"Master's Demonic Jawbone", 
			"Master's Inscribed Stone", 
			"Master's Runed Horn", 
			"Master's Hellish Handle", 
			"Master's Ghastly Candle", 
			"Master's Ancient Padding", 
			"Master's Ancient Chain Rings", 
			"Master's Ancient Bindings", 
			"Master's Demonic Scraps", 
			"Master's Demonic Plates", 
			"Master's Demonic Filling", 
			"Master's Carved Skull Padding", 
			"Master's Preserved Animal Fur", 
			"Master's Inscribed Bindings", 
			"Master's Imbued Visor", 
			"Master's Imbued Leather Folds", 
			"Master's Imbued Soles", 
			"Master's Demonhide Padding", 
			"Master's Demonhide Leather", 
			"Master's Demonhide Bindings", 
			"Master's Ghastly Visor", 
			"Master's Ghastly Leather", 
			"Master's Ghastly Bindings", 
			"Master's Druidic Preserved Beak", 
			"Master's Druidic Feathers", 
			"Master's Druidic Bindings", 
			"Master's Infernal Cloth Visor", 
			"Master's Infernal Cloth Folds", 
			"Master's Infernal Cloth Bindings", 
			"Master's Alluring Padding", 
			"Master's Alluring Amulet", 
			"Master's Alluring Bindings", 
			"Master's Essence", 
			"Master's Rune", 
			"Master's Soul", 
			"Master's Relic", 
			"Trash", 
			"Major Healing Potion", 
			"Major Energy Potion", 
			"Poison Potion", 
			"Potato Salad", 
			"Mutton Stew", 
			"Mutton Sandwich", 
			"Master's Shield", 
			"Master's Sarcophagus", 
			"Master's Caitiff Shield", 
			"Master's Facebreaker", 
			"Master's Tome of Spells", 
			"Master's Eye of Secrets", 
			"Master's Muisak", 
			"Master's Taproot", 
			"Master's Torch", 
			"Master's Mistcaller", 
			"Master's Leering Cane", 
			"Master's Cryptcandle", 
			"Master's Cape", 
			"Master's Bag", 
			"Undead Platemail Cape", 
			"Undead Leather Cape", 
			"Undead Cloth Cape", 
			"Keeper Platemail Cape", 
			"Keeper Leather Cape", 
			"Keeper Cloth Cape", 
			"Morgana Platemail Cape", 
			"Morgana Leather Cape", 
			"Morgana Cloth Cape", 
			"Master's Soldier Helmet", 
			"Master's Soldier Armor", 
			"Master's Soldier Boots", 
			"Master's Knight Helmet", 
			"Master's Knight Armor", 
			"Master's Knight Boots", 
			"Master's Guardian Helmet", 
			"Master's Guardian Armor", 
			"Master's Guardian Boots", 
			"Master's Graveguard Helmet", 
			"Master's Graveguard Armor", 
			"Master's Graveguard Boots", 
			"Master's Demon Helmet", 
			"Master's Demon Armor", 
			"Master's Demon Boots", 
			"Master's Judicator Helmet", 
			"Master's Judicator Armor", 
			"Master's Judicator Boots", 
			"Master's Mercenary Hood", 
			"Master's Mercenary Jacket", 
			"Master's Mercenary Shoes", 
			"Master's Hunter Hood", 
			"Master's Hunter Jacket", 
			"Master's Hunter Shoes", 
			"Master's Assassin Hood", 
			"Master's Assassin Jacket", 
			"Master's Assassin Shoes", 
			"Master's Stalker Hood", 
			"Master's Stalker Jacket", 
			"Master's Stalker Shoes", 
			"Master's Hellion Hood", 
			"Master's Hellion Jacket", 
			"Master's Hellion Shoes", 
			"Master's Specter Hood", 
			"Master's Specter Jacket", 
			"Master's Specter Shoes", 
			"Master's Scholar Cowl", 
			"Master's Scholar Robe", 
			"Master's Scholar Sandals", 
			"Master's Cleric Cowl", 
			"Master's Cleric Robe", 
			"Master's Cleric Sandals", 
			"Master's Mage Cowl", 
			"Master's Mage Robe", 
			"Master's Mage Sandals", 
			"Master's Druid Cowl", 
			"Master's Druid Robe", 
			"Master's Druid Sandals", 
			"Master's Fiend Cowl", 
			"Master's Fiend Robe", 
			"Master's Fiend Sandals", 
			"Master's Cultist Cowl", 
			"Master's Cultist Robe", 
			"Master's Cultist Sandals", 
			"Master's Royal Cowl", 
			"Master's Royal Robe", 
			"Master's Royal Sandals", 
			"Master's Royal Hood", 
			"Master's Royal Jacket", 
			"Master's Royal Shoes", 
			"Master's Royal Helmet", 
			"Master's Royal Armor", 
			"Master's Royal Boots", 
			"Master's Harvester Cap", 
			"Master's Harvester Garb", 
			"Master's Harvester Workboots", 
			"Master's Harvester Backpack", 
			"Master's Skinner Cap", 
			"Master's Skinner Garb", 
			"Master's Skinner Workboots", 
			"Master's Skinner Backpack", 
			"Master's Miner Cap", 
			"Master's Miner Garb", 
			"Master's Miner Workboots", 
			"Master's Miner Backpack", 
			"Master's Quarrier Cap", 
			"Master's Quarrier Garb", 
			"Master's Quarrier Workboots", 
			"Master's Quarrier Backpack", 
			"Master's Lumberjack Cap", 
			"Master's Lumberjack Garb", 
			"Master's Lumberjack Workboots", 
			"Master's Lumberjack Backpack", 
			"Master's Pickaxe", 
			"Master's Stone Hammer", 
			"Master's Axe", 
			"Master's Sickle", 
			"Master's Skinning Knife", 
			"Master's Demolition Hammer", 
			"Master's Bow", 
			"Master's Warbow", 
			"Master's Longbow", 
			"Master's Whispering Bow", 
			"Master's Wailing Bow", 
			"Master's Bow of Badon", 
			"Master's Crossbow", 
			"Master's Heavy Crossbow", 
			"Master's Light Crossbow", 
			"Master's Weeping Repeater", 
			"Master's Boltcasters", 
			"Master's Siegebow", 
			"Master's Cursed Staff", 
			"Master's Great Cursed Staff", 
			"Master's Demonic Staff", 
			"Master's Lifecurse Staff", 
			"Master's Cursed Skull", 
			"Master's Damnation Staff", 
			"Master's Fire Staff", 
			"Master's Great Fire Staff", 
			"Master's Infernal Staff", 
			"Master's Wildfire Staff", 
			"Master's Brimstone Staff", 
			"Master's Blazing Staff", 
			"Master's Frost Staff", 
			"Master's Great Frost Staff", 
			"Master's Glacial Staff", 
			"Master's Hoarfrost Staff", 
			"Master's Icicle Staff", 
			"Master's Permafrost Prism", 
			"Master's Arcane Staff", 
			"Master's Great Arcane Staff", 
			"Master's Enigmatic Staff", 
			"Master's Witchwork Staff", 
			"Master's Occult Staff", 
			"Master's Eye of Secrets", 
			"Master's Holy Staff", 
			"Master's Great Holy Staff", 
			"Master's Divine Staff", 
			"Master's Lifetouch Staff", 
			"Master's Fallen Staff", 
			"Master's Redemption Staff", 
			"Master's Nature Staff", 
			"Master's Great Nature Staff", 
			"Master's Wild Staff", 
			"Master's Druidic Staff", 
			"Master's Blight Staff", 
			"Master's Rampant Staff", 
			"Master's Dagger", 
			"Master's Dagger Pair", 
			"Master's Claws", 
			"Master's Bloodletter", 
			"Master's Black Hands", 
			"Master's Deathgivers", 
			"Master's Spear", 
			"Master's Pike", 
			"Master's Glaive", 
			"Master's Heron Spear", 
			"Master's Spirithunter", 
			"Master's Trinity Spear", 
			"Master's Battleaxe", 
			"Master's Greataxe", 
			"Master's Halberd", 
			"Master's Carrioncaller", 
			"Master's Infernal Scythe", 
			"Master's Bear Paws", 
			"Master's Broadsword", 
			"Master's Claymore", 
			"Master's Dual Swords", 
			"Master's Clarent Blade", 
			"Master's Carving Sword", 
			"Master's Galatine Pair", 
			"Master's Quarterstaff", 
			"Master's Iron-clad Staff", 
			"Master's Double Bladed Staff", 
			"Master's Black Monk Stave", 
			"Master's Soulscythe", 
			"Master's Staff of Balance", 
			"Master's Hammer", 
			"Master's Polehammer", 
			"Master's Great Hammer", 
			"Master's Tombhammer", 
			"Master's Forge Hammers", 
			"Master's Grovekeeper", 
			"Master's Mace", 
			"Master's Heavy Mace", 
			"Master's Morning Star", 
			"Master's Bedrock Mace", 
			"Master's Incubus Mace", 
			"Master's Camlann Mace", 
			"Master's Riding Horse", 
			"Master's Armored Horse", 
			"Master's Transport Ox", 
			"Master's Giant Stag", 
			"Yule Stag", 
			"Direwolf", 
			"Master's Repair Kit", 
			"Master's Bed", 
			"Master's Table", 
			"Encyclopedia of Power", 
			"Master Mercenary's Trophy", 
			"Stuffed Direwolf Head", 
			"Master Lumberjack's Journal (Partially Full)", 
			"Master Stonecutter's Journal (Partially Full)", 
			"Master Prospector's Journal (Partially Full)", 
			"Master Cropper's Journal (Partially Full)", 
			"Master Gamekeeper's Journal (Partially Full)", 
			"Master Blacksmith's Journal (Partially Full)", 
			"Master Fletcher's Journal (Partially Full)", 
			"Master Imbuer's Journal (Partially Full)", 
			"Master Tinker's Journal (Partially Full)", 
			"Master Mercenary's Journal (Partially Full)", 
			"Master's Generalist Trophy Journal (Partially Full)", 
			"Master Mercenary's Trophy Journal (Partially Full)", 
			"Master Gamekeeper's Trophy Journal (Partially Full)", 
			"Corn Seeds", 
			"Firetouched Mullein Seed", 
			"Grandmaster's Ox Calf", 
			"Grandmaster's Foal", 
			"Direboar Piglet", 
			"Piglet", 
			"Grandmaster's Horse", 
			"Grandmaster's Ox", 
			"Tame Direboar", 
			"Pig", 
			"Bundle of Corn", 
			"Firetouched Mullein", 
			"Grandmaster's Royal Sigil", 
			"Raw Pork", 
			"Corn Hooch", 
			"Ashenbark Logs", 
			"Uncommon Ashenbark Logs", 
			"Rare Ashenbark Logs", 
			"Exceptional Ashenbark Logs", 
			"Basalt", 
			"Meteorite Ore", 
			"Uncommon Meteorite Ore", 
			"Rare Meteorite Ore", 
			"Exceptional Meteorite Ore", 
			"Thick Hide", 
			"Uncommon Thick Hide", 
			"Rare Thick Hide", 
			"Exceptional Thick Hide", 
			"Sunflax", 
			"Uncommon Sunflax", 
			"Rare Sunflax", 
			"Exceptional Sunflax", 
			"Ashenbark Planks", 
			"Uncommon Ashenbark Planks", 
			"Rare Ashenbark Planks", 
			"Exceptional Ashenbark Planks", 
			"Basalt Block", 
			"Meteorite Steel Bar", 
			"Uncommon Meteorite Steel Bar", 
			"Rare Meteorite Steel Bar", 
			"Exceptional Meteorite Steel Bar", 
			"Reinforced Leather", 
			"Uncommon Reinforced Leather", 
			"Rare Reinforced Leather", 
			"Exceptional Reinforced Leather", 
			"Opulent Cloth", 
			"Uncommon Opulent Cloth", 
			"Rare Opulent Cloth", 
			"Exceptional Opulent Cloth", 
			"Grandmaster's Bloodforged Catalyst", 
			"Grandmaster's Hellish Sicklehead", 
			"Grandmaster's Occult Orb", 
			"Grandmaster's Demonic Arrowheads", 
			"Grandmaster's Carved bone", 
			"Grandmaster's Demonic Blade", 
			"Grandmaster's Reinforced Morgana Pole", 
			"Grandmaster's Alluring Bolts", 
			"Grandmaster's Keeper Axeheads", 
			"Grandmaster's Hellish Bolts", 
			"Grandmaster's Hellish Hammer Heads", 
			"Grandmaster's Cursed Blades", 
			"Grandmaster's Ghastly Blades", 
			"Grandmaster's Possessed Catalyst", 
			"Grandmaster's Burning Orb", 
			"Grandmaster's Morgana Halberd Head", 
			"Grandmaster's Ancient Hammer Head", 
			"Grandmaster's Infernal Harpoon Tip", 
			"Grandmaster's Possessed Scroll", 
			"Grandmaster's Infernal Scroll", 
			"Grandmaster's Ghastly Scroll", 
			"Grandmaster's Cursed Frozen Crystal", 
			"Grandmaster's Icicle Orb", 
			"Grandmaster's Unholy Scroll", 
			"Grandmaster's Black Leather", 
			"Grandmaster's Ghastly Arrows", 
			"Grandmaster's Imbued Mace Head", 
			"Grandmaster's Symbol of Blight", 
			"Grandmaster's Preserved Log", 
			"Grandmaster's Engraved Log", 
			"Grandmaster's Lost Crossbow Mechanism", 
			"Grandmaster's Preserved Rocks", 
			"Grandmaster's Cursed Jawbone", 
			"Grandmaster's Cursed Barbs", 
			"Grandmaster's Hellish Sicklehead Pair", 
			"Grandmaster's Lost Arcane Crystal", 
			"Grandmaster's Lost Cursed Crystal", 
			"Grandmaster's Wildfire Orb", 
			"Grandmaster's Hoarfrost Orb", 
			"Grandmaster's Infernal Mace Head", 
			"Grandmaster's Druidic Inscriptions", 
			"Grandmaster's Hardened Debole", 
			"Grandmaster's Runed Rock", 
			"Grandmaster's Bloodforged Blade", 
			"Grandmaster's Keeper Spearhead", 
			"Grandmaster's Ancient Shield Core", 
			"Grandmaster's Infernal Shield Core", 
			"Grandmaster's Bloodforged Spikes", 
			"Grandmaster's Alluring Crystal", 
			"Grandmaster's Demonic Jawbone", 
			"Grandmaster's Inscribed Stone", 
			"Grandmaster's Runed Horn", 
			"Grandmaster's Hellish Handle", 
			"Grandmaster's Ghastly Candle", 
			"Grandmaster's Ancient Padding", 
			"Grandmaster's Ancient Chain Rings", 
			"Grandmaster's Ancient Bindings", 
			"Grandmaster's Demonic Scraps", 
			"Grandmaster's Demonic Plates", 
			"Grandmaster's Demonic Filling", 
			"Grandmaster's Carved Skull Padding", 
			"Grandmaster's Preserved Animal Fur", 
			"Grandmaster's Inscribed Bindings", 
			"Grandmaster's Imbued Visor", 
			"Grandmaster's Imbued Leather Folds", 
			"Grandmaster's Imbued Soles", 
			"Grandmaster's Demonhide Padding", 
			"Grandmaster's Demonhide Leather", 
			"Grandmaster's Demonhide Bindings", 
			"Grandmaster's Ghastly Visor", 
			"Grandmaster's Ghastly Leather", 
			"Grandmaster's Ghastly Bindings", 
			"Grandmaster's Druidic Preserved Beak", 
			"Grandmaster's Druidic Feathers", 
			"Grandmaster's Druidic Bindings", 
			"Grandmaster's Infernal Cloth Visor", 
			"Grandmaster's Infernal Cloth Folds", 
			"Grandmaster's Infernal Cloth Bindings", 
			"Grandmaster's Alluring Padding", 
			"Grandmaster's Alluring Amulet", 
			"Grandmaster's Alluring Bindings", 
			"Grandmaster's Essence", 
			"Grandmaster's Rune", 
			"Grandmaster's Soul", 
			"Grandmaster's Relic", 
			"Trash", 
			"Major Gigantify Potion", 
			"Major Resistance Potion", 
			"Major Sticky Potion", 
			"Pork Pie", 
			"Pork Omelette", 
			"Grandmaster's Shield", 
			"Grandmaster's Sarcophagus", 
			"Grandmaster's Caitiff Shield", 
			"Grandmaster's Facebreaker", 
			"Grandmaster's Tome of Spells", 
			"Grandmaster's Eye of Secrets", 
			"Grandmaster's Muisak", 
			"Grandmaster's Taproot", 
			"Grandmaster's Torch", 
			"Grandmaster's Mistcaller", 
			"Grandmaster's Leering Cane", 
			"Grandmaster's Cryptcandle", 
			"Grandmaster's Cape", 
			"Grandmaster's Bag", 
			"Grandmaster's Soldier Helmet", 
			"Grandmaster's Soldier Armor", 
			"Grandmaster's Soldier Boots", 
			"Grandmaster's Knight Helmet", 
			"Grandmaster's Knight Armor", 
			"Grandmaster's Knight Boots", 
			"Grandmaster's Guardian Helmet", 
			"Grandmaster's Guardian Armor", 
			"Grandmaster's Guardian Boots", 
			"Grandmaster's Graveguard Helmet", 
			"Grandmaster's Graveguard Armor", 
			"Grandmaster's Graveguard Boots", 
			"Grandmaster's Demon Helmet", 
			"Grandmaster's Demon Armor", 
			"Grandmaster's Demon Boots", 
			"Grandmaster's Judicator Helmet", 
			"Grandmaster's Judicator Armor", 
			"Grandmaster's Judicator Boots", 
			"Grandmaster's Mercenary Hood", 
			"Grandmaster's Mercenary Jacket", 
			"Grandmaster's Mercenary Shoes", 
			"Grandmaster's Hunter Hood", 
			"Grandmaster's Hunter Jacket", 
			"Grandmaster's Hunter Shoes", 
			"Grandmaster's Assassin Hood", 
			"Grandmaster's Assassin Jacket", 
			"Grandmaster's Assassin Shoes", 
			"Grandmaster's Stalker Hood", 
			"Grandmaster's Stalker Jacket", 
			"Grandmaster's Stalker Shoes", 
			"Grandmaster's Hellion Hood", 
			"Grandmaster's Hellion Jacket", 
			"Grandmaster's Hellion Shoes", 
			"Grandmaster's Specter Hood", 
			"Grandmaster's Specter Jacket", 
			"Grandmaster's Specter Shoes", 
			"Grandmaster's Scholar Cowl", 
			"Grandmaster's Scholar Robe", 
			"Grandmaster's Scholar Sandals", 
			"Grandmaster's Cleric Cowl", 
			"Grandmaster's Cleric Robe", 
			"Grandmaster's Cleric Sandals", 
			"Grandmaster's Mage Cowl", 
			"Grandmaster's Mage Robe", 
			"Grandmaster's Mage Sandals", 
			"Grandmaster's Druid Cowl", 
			"Grandmaster's Druid Robe", 
			"Grandmaster's Druid Sandals", 
			"Grandmaster's Fiend Cowl", 
			"Grandmaster's Fiend Robe", 
			"Grandmaster's Fiend Sandals", 
			"Grandmaster's Cultist Cowl", 
			"Grandmaster's Cultist Robe", 
			"Grandmaster's Cultist Sandals", 
			"Grandmaster's Royal Cowl", 
			"Grandmaster's Royal Robe", 
			"Grandmaster's Royal Sandals", 
			"Grandmaster's Royal Hood", 
			"Grandmaster's Royal Jacket", 
			"Grandmaster's Royal Shoes", 
			"Grandmaster's Royal Helmet", 
			"Grandmaster's Royal Armor", 
			"Grandmaster's Royal Boots", 
			"Grandmaster's Harvester Cap", 
			"Grandmaster's Harvester Garb", 
			"Grandmaster's Harvester Workboots", 
			"Grandmaster's Harvester Backpack", 
			"Grandmaster's Skinner Cap", 
			"Grandmaster's Skinner Garb", 
			"Grandmaster's Skinner Workboots", 
			"Grandmaster's Skinner Backpack", 
			"Grandmaster's Miner Cap", 
			"Grandmaster's Miner Garb", 
			"Grandmaster's Miner Workboots", 
			"Grandmaster's Miner Backpack", 
			"Grandmaster's Quarrier Cap", 
			"Grandmaster's Quarrier Garb", 
			"Grandmaster's Quarrier Workboots", 
			"Grandmaster's Quarrier Backpack", 
			"Grandmaster's Lumberjack Cap", 
			"Grandmaster's Lumberjack Garb", 
			"Grandmaster's Lumberjack Workboots", 
			"Grandmaster's Lumberjack Backpack", 
			"Grandmaster's Pickaxe", 
			"Grandmaster's Stone Hammer", 
			"Grandmaster's Axe", 
			"Grandmaster's Sickle", 
			"Grandmaster's Skinning Knife", 
			"Grandmaster's Demolition Hammer", 
			"Grandmaster's Bow", 
			"Grandmaster's Warbow", 
			"Grandmaster's Longbow", 
			"Grandmaster's Whispering Bow", 
			"Grandmaster's Wailing Bow", 
			"Grandmaster's Bow of Badon", 
			"Grandmaster's Crossbow", 
			"Grandmaster's Heavy Crossbow", 
			"Grandmaster's Light Crossbow", 
			"Grandmaster's Weeping Repeater", 
			"Grandmaster's Boltcasters", 
			"Grandmaster's Siegebow", 
			"Grandmaster's Cursed Staff", 
			"Grandmaster's Great Cursed Staff", 
			"Grandmaster's Demonic Staff", 
			"Grandmaster's Lifecurse Staff", 
			"Grandmaster's Cursed Skull", 
			"Grandmaster's Damnation Staff", 
			"Grandmaster's Fire Staff", 
			"Grandmaster's Great Fire Staff", 
			"Grandmaster's Infernal Staff", 
			"Grandmaster's Wildfire Staff", 
			"Grandmaster's Brimstone Staff", 
			"Grandmaster's Blazing Staff", 
			"Grandmaster's Frost Staff", 
			"Grandmaster's Great Frost Staff", 
			"Grandmaster's Glacial Staff", 
			"Grandmaster's Hoarfrost Staff", 
			"Grandmaster's Icicle Staff", 
			"Grandmaster's Permafrost Prism", 
			"Grandmaster's Arcane Staff", 
			"Grandmaster's Great Arcane Staff", 
			"Grandmaster's Enigmatic Staff", 
			"Grandmaster's Witchwork Staff", 
			"Grandmaster's Occult Staff", 
			"Grandmaster's Eye of Secrets", 
			"Grandmaster's Holy Staff", 
			"Grandmaster's Great Holy Staff", 
			"Grandmaster's Divine Staff", 
			"Grandmaster's Lifetouch Staff", 
			"Grandmaster's Fallen Staff", 
			"Grandmaster's Redemption Staff", 
			"Grandmaster's Nature Staff", 
			"Grandmaster's Great Nature Staff", 
			"Grandmaster's Wild Staff", 
			"Grandmaster's Druidic Staff", 
			"Grandmaster's Blight Staff", 
			"Grandmaster's Rampant Staff", 
			"Grandmaster's Dagger", 
			"Grandmaster's Dagger Pair", 
			"Grandmaster's Claws", 
			"Grandmaster's Bloodletter", 
			"Grandmaster's Black Hands", 
			"Grandmaster's Deathgivers", 
			"Grandmaster's Spear", 
			"Grandmaster's Pike", 
			"Grandmaster's Glaive", 
			"Grandmaster's Heron Spear", 
			"Grandmaster's Spirithunter", 
			"Grandmaster's Trinity Spear", 
			"Grandmaster's Battleaxe", 
			"Grandmaster's Greataxe", 
			"Grandmaster's Halberd", 
			"Grandmaster's Carrioncaller", 
			"Grandmaster's Infernal Scythe", 
			"Grandmaster's Bear Paws", 
			"Grandmaster's Broadsword", 
			"Grandmaster's Claymore", 
			"Grandmaster's Dual Swords", 
			"Grandmaster's Clarent Blade", 
			"Grandmaster's Carving Sword", 
			"Grandmaster's Galatine Pair", 
			"Grandmaster's Quarterstaff", 
			"Grandmaster's Iron-clad Staff", 
			"Grandmaster's Double Bladed Staff", 
			"Grandmaster's Black Monk Stave", 
			"Grandmaster's Soulscythe", 
			"Grandmaster's Staff of Balance", 
			"Grandmaster's Hammer", 
			"Grandmaster's Polehammer", 
			"Grandmaster's Great Hammer", 
			"Grandmaster's Tombhammer", 
			"Grandmaster's Forge Hammers", 
			"Grandmaster's Grovekeeper", 
			"Grandmaster's Mace", 
			"Grandmaster's Heavy Mace", 
			"Grandmaster's Morning Star", 
			"Grandmaster's Bedrock Mace", 
			"Grandmaster's Incubus Mace", 
			"Grandmaster's Camlann Mace", 
			"Grandmaster's Riding Horse", 
			"Grandmaster's Armored Horse", 
			"Grandmaster's Transport Ox", 
			"Saddled Direboar", 
			"Grandmaster's Repair Kit", 
			"Grandmaster's Bed", 
			"Grandmaster's Table", 
			"Occult Octavo", 
			"Grandmaster Mercenary's Trophy", 
			"Stuffed Direboar Head", 
			"Grandmaster Lumberjack's Journal (Partially Full)", 
			"Grandmaster Stonecutter's Journal (Partially Full)", 
			"Grandmaster Prospector's Journal (Partially Full)", 
			"Grandmaster Cropper's Journal (Partially Full)", 
			"Grandmaster Gamekeeper's Journal (Partially Full)", 
			"Grandmaster Blacksmith's Journal (Partially Full)", 
			"Grandmaster Fletcher's Journal (Partially Full)", 
			"Grandmaster Imbuer's Journal (Partially Full)", 
			"Grandmaster Tinker's Journal (Partially Full)", 
			"Grandmaster Mercenary's Journal (Partially Full)", 
			"Grandmaster's Generalist Trophy Journal (Partially Full)", 
			"Grandmaster Mercenary's Trophy Journal (Partially Full)", 
			"Grandmaster Gamekeeper's Trophy Journal (Partially Full)", 
			"Pumpkin Seeds", 
			"Ghoul Yarrow Seed", 
			"Elder's Ox Calf", 
			"Elder's Foal", 
			"Direbear Cub", 
			"albion.ITEMS_T8_FARM_SWAMPDRAGON_BABY", 
			"Mammoth Calf", 
			"Ghostwolf Pup", 
			"Calf", 
			"Elder's Horse", 
			"Elder's Ox", 
			"Tame Direbear", 
			"albion.ITEMS_T8_FARM_SWAMPDRAGON_GROWN", 
			"Tame Mammoth", 
			"Tame Ghostwolf", 
			"Cow", 
			"Spectral Mask", 
			"Sacred Bone Marrow", 
			"Infernal Horseshoes", 
			"albion.ITEMS_T8_MOUNTUPGRADE_COMMAND_MAMMOTH", 
			"Pumpkin", 
			"Ghoul Yarrow", 
			"Cow's Milk", 
			"Elder's Royal Sigil", 
			"Raw Beef", 
			"Cow's Butter", 
			"Pumpkin Moonshine", 
			"Whitewood Logs", 
			"Uncommon Whitewood Logs", 
			"Rare Whitewood Logs", 
			"Exceptional Whitewood Logs", 
			"Marble", 
			"Adamantium Ore", 
			"Uncommon Adamantium Ore", 
			"Rare Adamantium Ore", 
			"Exceptional Adamantium Ore", 
			"Resilient Hide", 
			"Uncommon Resilient Hide", 
			"Rare Resilient Hide", 
			"Exceptional Resilient Hide", 
			"Ghost Hemp", 
			"Uncommon Ghost Hemp", 
			"Rare Ghost Hemp", 
			"Exceptional Ghost Hemp", 
			"Whitewood Planks", 
			"Uncommon Whitewood Planks", 
			"Rare Whitewood Planks", 
			"Exceptional Whitewood Planks", 
			"Marble Block", 
			"Adamantium Steel Bar", 
			"Uncommon Adamantium Steel Bar", 
			"Rare Adamantium Steel Bar", 
			"Exceptional Adamantium Steel Bar", 
			"Fortified Leather", 
			"Uncommon Fortified Leather", 
			"Rare Fortified Leather", 
			"Exceptional Fortified Leather", 
			"Baroque Cloth", 
			"Uncommon Baroque Cloth", 
			"Rare Baroque Cloth", 
			"Exceptional Baroque Cloth", 
			"Elder's Bloodforged Catalyst", 
			"Elder's Hellish Sicklehead", 
			"Elder's Occult Orb", 
			"Elder's Demonic Arrowheads", 
			"Elder's Carved bone", 
			"Elder's Demonic Blade", 
			"Elder's Reinforced Morgana Pole", 
			"Elder's Alluring Bolts", 
			"Elder's Keeper Axeheads", 
			"Elder's Hellish Bolts", 
			"Elder's Hellish Hammer Heads", 
			"Elder's Cursed Blades", 
			"Elder's Ghastly Blades", 
			"Elder's Possessed Catalyst", 
			"Elder's Burning Orb", 
			"Elder's Morgana Halberd Head", 
			"Elder's Ancient Hammer Head", 
			"Elder's Infernal Harpoon Tip", 
			"Elder's Possessed Scroll", 
			"Elder's Infernal Scroll", 
			"Elder's Ghastly Scroll", 
			"Elder's Cursed Frozen Crystal", 
			"Elder's Icicle Orb", 
			"Elder's Unholy Scroll", 
			"Elder's Black Leather", 
			"Elder's Ghastly Arrows", 
			"Elder's Imbued Mace Head", 
			"Elder's Symbol of Blight", 
			"Elder's Preserved Log", 
			"Elder's Engraved Log", 
			"Elder's Lost Crossbow Mechanism", 
			"Elder's Preserved Rocks", 
			"Elder's Cursed Jawbone", 
			"Elder's Cursed Barbs", 
			"Elder's Hellish Sicklehead Pair", 
			"Elder's Lost Arcane Crystal", 
			"Elder's Lost Cursed Crystal", 
			"Elder's Wildfire Orb", 
			"Elder's Hoarfrost Orb", 
			"Elder's Infernal Mace Head", 
			"Elder's Druidic Inscriptions", 
			"Elder's Hardened Debole", 
			"Elder's Runed Rock", 
			"Elder's Bloodforged Blade", 
			"Elder's Keeper Spearhead", 
			"Elder's Ancient Shield Core", 
			"Elder's Infernal Shield Core", 
			"Elder's Bloodforged Spikes", 
			"Elder's Alluring Crystal", 
			"Elder's Demonic Jawbone", 
			"Elder's Inscribed Stone", 
			"Elder's Runed Horn", 
			"Elder's Hellish Handle", 
			"Elder's Ghastly Pimele", 
			"Elder's Ancient Padding", 
			"Elder's Ancient Chain Rings", 
			"Elder's Ancient Bindings", 
			"Elder's Demonic Scraps", 
			"Elder's Demonic Plates", 
			"Elder's Demonic Filling", 
			"Elder's Carved Skull Padding", 
			"Elder's Preserved Animal Fur", 
			"Elder's Inscribed Bindings", 
			"Elder's Imbued Visor", 
			"Elder's Imbued Leather Folds", 
			"Elder's Imbued Soles", 
			"Elder's Demonhide Padding", 
			"Elder's Demonhide Leather", 
			"Elder's Demonhide Bindings", 
			"Elder's Ghastly Visor", 
			"Elder's Ghastly Leather", 
			"Elder's Ghastly Bindings", 
			"Elder's Druidic Preserved Beak", 
			"Elder's Druidic Feathers", 
			"Elder's Druidic Bindings", 
			"Elder's Infernal Cloth Visor", 
			"Elder's Infernal Cloth Folds", 
			"Elder's Infernal Cloth Bindings", 
			"Elder's Alluring Padding", 
			"Elder's Alluring Amulet", 
			"Elder's Alluring Bindings", 
			"Elder's Essence", 
			"Elder's Rune", 
			"Elder's Soul", 
			"Elder's Relic", 
			"Trash", 
			"Major Poison Potion", 
			"Invisibility Potion", 
			"Beef Stew", 
			"Beef Sandwich", 
			"Elder's Shield", 
			"Elder's Sarcophagus", 
			"Elder's Caitiff Shield", 
			"Elder's Facebreaker", 
			"Elder's Tome of Spells", 
			"Elder's Eye of Secrets", 
			"Elder's Muisak", 
			"Elder's Taproot", 
			"Elder's Torch", 
			"Elder's Mistcaller", 
			"Elder's Leering Cane", 
			"Elder's Cryptcandle", 
			"Elder's Cape", 
			"Elder's Bag", 
			"Elder's Soldier Helmet", 
			"Elder's Soldier Armor", 
			"Elder's Soldier Boots", 
			"Elder's Knight Helmet", 
			"Elder's Knight Armor", 
			"Elder's Knight Boots", 
			"Elder's Guardian Helmet", 
			"Elder's Guardian Armor", 
			"Elder's Guardian Boots", 
			"Elder's Graveguard Helmet", 
			"Elder's Graveguard Armor", 
			"Elder's Graveguard Boots", 
			"Elder's Demon Helmet", 
			"Elder's Demon Armor", 
			"Elder's Demon Boots", 
			"Elder's Judicator Helmet", 
			"Elder's Judicator Armor", 
			"Elder's Judicator Boots", 
			"Elder's Mercenary Hood", 
			"Elder's Mercenary Jacket", 
			"Elder's Mercenary Shoes", 
			"Elder's Hunter Hood", 
			"Elder's Hunter Jacket", 
			"Elder's Hunter Shoes", 
			"Elder's Assassin Hood", 
			"Elder's Assassin Jacket", 
			"Elder's Assassin Shoes", 
			"Elder's Stalker Hood", 
			"Elder's Stalker Jacket", 
			"Elder's Stalker Shoes", 
			"Elder's Hellion Hood", 
			"Elder's Hellion Jacket", 
			"Elder's Hellion Shoes", 
			"Elder's Specter Hood", 
			"Elder's Specter Jacket", 
			"Elder's Specter Shoes", 
			"Elder's Scholar Cowl", 
			"Elder's Scholar Robe", 
			"Elder's Scholar Sandals", 
			"Elder's Cleric Cowl", 
			"Elder's Cleric Robe", 
			"Elder's Cleric Sandals", 
			"Elder's Mage Cowl", 
			"Elder's Mage Robe", 
			"Elder's Mage Sandals", 
			"Elder's Druid Cowl", 
			"Elder's Druid Robe", 
			"Elder's Druid Sandals", 
			"Elder's Fiend Cowl", 
			"Elder's Fiend Robe", 
			"Elder's Fiend Sandals", 
			"Elder's Cultist Cowl", 
			"Elder's Cultist Robe", 
			"Elder's Cultist Sandals", 
			"Elder's Royal Cowl", 
			"Elder's Royal Robe", 
			"Elder's Royal Sandals", 
			"Elder's Royal Hood", 
			"Elder's Royal Jacket", 
			"Elder's Royal Shoes", 
			"Elder's Royal Helmet", 
			"Elder's Royal Armor", 
			"Elder's Royal Boots", 
			"Elder's Harvester Cap", 
			"Elder's Harvester Garb", 
			"Elder's Harvester Workboots", 
			"Elder's Harvester Backpack", 
			"Elder's Skinner Cap", 
			"Elder's Skinner Garb", 
			"Elder's Skinner Workboots", 
			"Elder's Skinner Backpack", 
			"Elder's Miner Cap", 
			"Elder's Miner Garb", 
			"Elder's Miner Workboots", 
			"Elder's Miner Backpack", 
			"Elder's Quarrier Cap", 
			"Elder's Quarrier Garb", 
			"Elder's Quarrier Workboots", 
			"Elder's Quarrier Backpack", 
			"Elder's Lumberjack Cap", 
			"Elder's Lumberjack Garb", 
			"Elder's Lumberjack Workboots", 
			"Elder's Lumberjack Backpack", 
			"Elder's Pickaxe", 
			"Elder's Stone Hammer", 
			"Elder's Axe", 
			"Elder's Sickle", 
			"Elder's Skinning Knife", 
			"Elder's Demolition Hammer", 
			"Elder's Bow", 
			"Elder's Warbow", 
			"Elder's Longbow", 
			"Elder's Whispering Bow", 
			"Elder's Wailing Bow", 
			"Elder's Bow of Badon", 
			"Elder's Crossbow", 
			"Elder's Heavy Crossbow", 
			"Elder's Light Crossbow", 
			"Elder's Weeping Repeater", 
			"Elder's Boltcasters", 
			"Elder's Siegebow", 
			"Elder's Cursed Staff", 
			"Elder's Great Cursed Staff", 
			"Elder's Demonic Staff", 
			"Elder's Lifecurse Staff", 
			"Elder's Cursed Skull", 
			"Elder's Damnation Staff", 
			"Elder's Fire Staff", 
			"Elder's Great Fire Staff", 
			"Elder's Infernal Staff", 
			"Elder's Wildfire Staff", 
			"Elder's Brimstone Staff", 
			"Elder's Blazing Staff", 
			"Elder's Frost Staff", 
			"Elder's Great Frost Staff", 
			"Elder's Glacial Staff", 
			"Elder's Hoarfrost Staff", 
			"Elder's Icicle Staff", 
			"Elder's Permafrost Prism", 
			"Elder's Arcane Staff", 
			"Elder's Great Arcane Staff", 
			"Elder's Enigmatic Staff", 
			"Elder's Witchwork Staff", 
			"Elder's Occult Staff", 
			"Elder's Eye of Secrets", 
			"Elder's Holy Staff", 
			"Elder's Great Holy Staff", 
			"Elder's Divine Staff", 
			"Elder's Lifetouch Staff", 
			"Elder's Fallen Staff", 
			"Elder's Redemption Staff", 
			"Elder's Nature Staff", 
			"Elder's Great Nature Staff", 
			"Elder's Wild Staff", 
			"Elder's Druidic Staff", 
			"Elder's Blight Staff", 
			"Elder's Rampant Staff", 
			"Elder's Dagger", 
			"Elder's Dagger Pair", 
			"Elder's Claws", 
			"Elder's Bloodletter", 
			"Elder's Black Hands", 
			"Elder's Deathgivers", 
			"Elder's Spear", 
			"Elder's Pike", 
			"Elder's Glaive", 
			"Elder's Heron Spear", 
			"Elder's Spirithunter", 
			"Elder's Trinity Spear", 
			"Elder's Battleaxe", 
			"The Hand of Khor", 
			"Elder's Halberd", 
			"Elder's Carrioncaller", 
			"Elder's Infernal Scythe", 
			"Elder's Bear Paws", 
			"Elder's Broadsword", 
			"Elder's Claymore", 
			"Elder's Dual Swords", 
			"Elder's Clarent Blade", 
			"Elder's Carving Sword", 
			"Elder's Galatine Pair", 
			"Elder's Quarterstaff", 
			"Elder's Iron-clad Staff", 
			"Elder's Double Bladed Staff", 
			"Elder's Black Monk Stave", 
			"Elder's Soulscythe", 
			"Elder's Staff of Balance", 
			"Elder's Hammer", 
			"Elder's Polehammer", 
			"Elder's Great Hammer", 
			"Elder's Tombhammer", 
			"Elder's Forge Hammers", 
			"Elder's Grovekeeper", 
			"Elder's Mace", 
			"Elder's Heavy Mace", 
			"Elder's Morning Star", 
			"Elder's Bedrock Mace", 
			"Elder's Incubus Mace", 
			"Elder's Camlann Mace", 
			"Elder's Riding Horse", 
			"Elder's Armored Horse", 
			"Elder's Transport Ox", 
			"Ghostwolf", 
			"Saddled Direbear", 
			"Elder's Transport Mammoth", 
			"Elder's Command Mammoth", 
			"albion.ITEMS_T8_MOUNT_SWAMPDRAGON", 
			"Spectral Bonehorse", 
			"Rageclaw", 
			"Nightmare", 
			"Elder's Repair Kit", 
			"Elder's Bed", 
			"Elder's Table", 
			"albion.ITEMS_UNIQUE_ALTAR_OF_CHEATING", 
			"Ledger of Truths", 
			"Elder Mercenary's Trophy", 
			"Stuffed Direbear Head", 
			"Elder Lumberjack's Journal (Partially Full)", 
			"Elder Stonecutter's Journal (Partially Full)", 
			"Elder Prospector's Journal (Partially Full)", 
			"Elder Cropper's Journal (Partially Full)", 
			"Elder Gamekeeper's Journal (Partially Full)", 
			"Elder Blacksmith's Journal (Partially Full)", 
			"Elder Fletcher's Journal (Partially Full)", 
			"Elder Imbuer's Journal (Partially Full)", 
			"Elder Tinker's Journal (Partially Full)", 
			"Elder Mercenary's Journal (Partially Full)", 
			"Elder's Generalist Trophy Journal (Partially Full)", 
			"Elder Mercenary's Trophy Journal (Partially Full)", 
			"Elder Gamekeeper's Trophy Journal (Partially Full)"
	};
	ArrayList<String> possibleNamesAsList = new ArrayList<String>(Arrays.asList(possibleNames));
	public OCR(){
		comma = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/,");
		zero = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/0");
		one = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/1");
		two = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/2");
		three = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/3");
		four = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/4");
		five = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/5");
		six = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/6");
		seven = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/7");
		eight = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/8");
		nine = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/numbers/9");

		hyphen = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/'/cleaned");
		a = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/a/cleaned");
		b = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/b/cleaned");
		c = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/c/cleaned");
		d = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/d/cleaned");
		e = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/e/cleaned");
		f = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/f/cleaned");
		g = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/g/cleaned");
		h = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/h/cleaned");
		i = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/i/cleaned");
		j = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/j/cleaned");
		k = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/k/cleaned");
		l = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/l/cleaned");
		m = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/m/cleaned");
		n = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/n/cleaned");
		o = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/o/cleaned");
		p = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/p/cleaned");
		q = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/q/cleaned");
		r = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/r/cleaned");
		s = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/s/cleaned");
		t = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/t/cleaned");
		u = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/u/cleaned");
		v = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/v/cleaned");
		w = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/w/cleaned");
		x = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/x/cleaned");
		y = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/y/cleaned");
		z = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/z/cleaned");

		fe = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/fe/cleaned");
		fo = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/fo/cleaned");
		fy = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/fy/cleaned");
		rd = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/rd/cleaned");
		re = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/re/cleaned");
		rg = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/rg/cleaned");
		rh = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/rh/cleaned");
		ro = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/ro/cleaned");
		rs = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/rs/cleaned");
		ry = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/ry/cleaned");
		rys = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/rys/cleaned");
		te = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/te/cleaned");
		to = GamePanel.loadImages(GamePanel.baseDirectory+"/characters/to/cleaned");
	}
	public boolean checkForMatch(BufferedImage img, ArrayList<BufferedImage> possibilities){
		//int cuttoff = 10;
		for(int cuttoff = 0; cuttoff<50; cuttoff += 10){
			for(int i = 0; i<possibilities.size(); i++){
				int count = 0;
				for(int x = 0; x<img.getWidth(); x++){
					for(int y = 0; y<img.getHeight(); y++){
						if(img.getRGB(x, y) != possibilities.get(i).getRGB(x, y)){
							count++;
						}
						if(count>cuttoff) break;
					}
					if(count>cuttoff) break;
				}
				if(count<cuttoff) return true;
			}
		}
		return false;
	}
	public String readImageNumber(BufferedImage img){
		if(checkForMatch(img, zero)) return "0";
		else if(checkForMatch(img, one)) return "1";
		else if(checkForMatch(img, two)) return "2";
		else if(checkForMatch(img, three)) return "3";
		else if(checkForMatch(img, four)) return "4";
		else if(checkForMatch(img, five)) return "5";
		else if(checkForMatch(img, six)) return "6";
		else if(checkForMatch(img, seven)) return "7";
		else if(checkForMatch(img, eight)) return "8";
		else if(checkForMatch(img, nine)) return "9";
		else if(checkForMatch(img, comma)) return "";
		return "_";
	}
	public String readImageText(BufferedImage img){

		if(checkForMatch(img, hyphen)) return "'";
		else if(checkForMatch(img, a)) return "a";
		else if(checkForMatch(img, b)) return "b";
		else if(checkForMatch(img, c)) return "c";
		else if(checkForMatch(img, d)) return "d";
		else if(checkForMatch(img, e)) return "e";
		else if(checkForMatch(img, f)) return "f";
		else if(checkForMatch(img, g)) return "g";
		else if(checkForMatch(img, h)) return "h";
		else if(checkForMatch(img, i)) return "i";
		else if(checkForMatch(img, j)) return "j";
		else if(checkForMatch(img, k)) return "k";
		else if(checkForMatch(img, l)) return "l";
		else if(checkForMatch(img, m)) return "m";
		else if(checkForMatch(img, n)) return "n";
		else if(checkForMatch(img, o)) return "o";
		else if(checkForMatch(img, p)) return "p";
		else if(checkForMatch(img, q)) return "q";
		else if(checkForMatch(img, t)) return "t";
		else if(checkForMatch(img, r)) return "r";
		else if(checkForMatch(img, s)) return "s";
		else if(checkForMatch(img, u)) return "u";
		else if(checkForMatch(img, v)) return "v";
		else if(checkForMatch(img, w)) return "w";
		else if(checkForMatch(img, x)) return "x";
		else if(checkForMatch(img, y)) return "y";
		else if(checkForMatch(img, z)) return "z";

		else if(checkForMatch(img, fe)) return "fe";
		else if(checkForMatch(img, fo)) return "fo";
		else if(checkForMatch(img, fy)) return "fy";
		else if(checkForMatch(img, rd)) return "rd";
		else if(checkForMatch(img, re)) return "re";
		else if(checkForMatch(img, rg)) return "rg";
		else if(checkForMatch(img, rh)) return "rh";
		else if(checkForMatch(img, ro)) return "ro";
		else if(checkForMatch(img, rs)) return "rs";
		else if(checkForMatch(img, ry)) return "ry";
		else if(checkForMatch(img, rys)) return "rys";
		else if(checkForMatch(img, te)) return "te";
		else if(checkForMatch(img, to)) return "to";
		return "_";
	}
	//replace last characters
	public String rlc(String str, String req, String replacement){
		int amt = req.length();
		if(str.length()>amt && str.substring(str.length()-amt, str.length()).equalsIgnoreCase(req))
			str = str.substring(0, str.length()-amt)+replacement;
		return str;
	}
	public String getNameFromOCR(String str){
		str = str.replace("boi", "bol");
		str = str.replace("br'", "bt'");
		str = str.replace("a''e", "alle");
		str = str.replace("sc__he", "scythe");
		str = str.replace("pr'", "pt'");
		str = str.replace("s_ff", "staff");
		str = str.replace("adep_s", "adept's");
		str = str.replace("secre_", "secrets");
		str = str.replace("e_per", "exper");
		str = str.replace("r's", "t's");
		str = str.replace("bemon", "demon");
		str = str.replace("c_perr", "expert");
		str = str.replace("r_or", "rmor");
		str = str.replace("_rmor", "armor");
		str = str.replace("c_pe", "expe");
		str = str.replace("e_p_", "expe");
		str = str.replace("ri'", "rt'");
		str = str.replace("t'_", "t's");
		str = str.replace("i'_", "t's");
		str = str.replace("r'", "t'");
		str = str.replace("h_'m", "helm");
		str = str.replace("helm_", "helme");
		str = str.replace("em_n", "emon");
		str = str.replace("_dept", "adept");
		str = str.replace("__ept'", "adept'");
		str = str.replace("___pt'", "adept'");
		str = str.replace("sa_an", "sarcan");
		str = str.replace("bfi", "bri");
		str = str.replace("____t'", "adept'");
		str = str.replace("_____t'", "expert'");
		str = str.replace("s__f", "staff");
		str = str.replace("ade__s", "adept's");
		str = str.replace("iac", "jac");
		str = str.replace("af__r", "armor");
		str = str.replace("e'mer", "armor");
		str = str.replace("boo_", "boots");
		str = str.replace("__ufn", "journ");
		str = str.replace("__urn", "journ");
		str = str.replace("__n'_", "man's");
		str = str.replace("ourn_____", "ourneyman");
		str = str.replace("n'_", "n's");
		str = str.replace("c______", "crossbow");
		str = str.replace("cro____", "crossbow");
		str = str.replace("cm_____", "crossbow");
		str = str.replace("_f_____", "crossbow");
		str = str.replace("ma_'", "man'");
		str = str.replace("m__'", "man'");
		str = str.replace("a_'", "an'");
		str = str.replace("b'", "n'");
		str = str.replace("s_fr", "staff");
		str = str.replace("h_'_s", "holys");
		str = str.replace("'_u", "jou");
		str = str.replace("jouf", "jour");
		str = str.replace("jout", "jour");
		str = str.replace("_ourn", "journ");
		str = str.replace("'e", "ie");
		str = str.replace("e'd", "eld");
		str = str.replace("", "");
		str = rlc(str, "__b_", "robe");
		str = str.replace("n'_", "n's");
		str = rlc(str, "rr", "ff");
		str = str.replace("s_h", "sch");
		str = str.replace("'i", "n");
		str = rlc(str, "___ff", "staff");
		str = str.replace("'s___r", "'squarter");
		str = str.replace("sc_p", "scrap");
		str = rlc(str, "s_w", "stew");
		str = str.replace("o'a", "ola");
		str = rlc(str, "owi", "owl");
		str = rlc(str, "dais", "dals");
		str = str.replace("fcow", "rcow");
		str = str.replace("harmor", "helmet");
		str = rlc(str, "_aci_e", "jacket");
		str = rlc(str, "ys_'", "ystal");
		str = str.replace("a_ane", "arcane");
		str = str.replace("in__ed", "inforced");
		str = rlc(str, "o_e", "ole");
		str = rlc(str,"c_s_i", "crystal");
		str = str.replace("et'", "er'");
		str = str.replace("eft'", "ert'");
		str = rlc(str, "anie", "able");
		str = rlc(str, "poti", "potion");
		str = rlc(str, "potio", "potion");
		str = str.replace("_aven", "raven");
		str = str.replace("srabd", "stand");
		str = str.replace("_a_eh", "raven");
		str = str.replace("nsrab", "nstan");
		str = str.replace("impie", "imple");
		str = str.replace("b_zi", "blazi");
		str = str.replace("wiid", "wild");
		str = str.replace("dnr", "dfir");
		str = str.replace("g'a", "gla");
		
		//System.out.println("DISTANCE IS: "+distance("abcdefg", "abc"));
		double smallestDistance=-1;
		int indexOfSmallestDistance = 0;
		//for each possible name
		for(int i = 0; i<possibleNames.length; i++){
			if(Math.abs(possibleNames[i].length() - str.length()) < 94){

				double dist = distance(str, possibleNames[i]);
				if(dist < smallestDistance || smallestDistance == -1){
					smallestDistance = dist;
					indexOfSmallestDistance = i;
				}

			}
		}
		System.out.println("str was: "+str+", smallest distance: "+smallestDistance+", would have guessed: "+possibleNames[indexOfSmallestDistance]);
		if(smallestDistance<=3){
			return str;
		}



		return possibleNames[indexOfSmallestDistance];
	}
	public final double distance(final String s1, final String s2) {
		if (s1 == null) {
			throw new NullPointerException("s1 must not be null");
		}

		if (s2 == null) {
			throw new NullPointerException("s2 must not be null");
		}

		if (s1.equals(s2)) {
			return 0;
		}

		if (s1.length() == 0) {
			return s2.length();
		}

		if (s2.length() == 0) {
			return s1.length();
		}

		// create two work vectors of integer distances
		int[] v0 = new int[s2.length() + 1];
		int[] v1 = new int[s2.length() + 1];
		int[] vtemp;

		// initialize v0 (the previous row of distances)
		// this row is A[0][i]: edit distance for an empty s
		// the distance is just the number of characters to delete from t
		for (int i = 0; i < v0.length; i++) {
			v0[i] = i;
		}

		for (int i = 0; i < s1.length(); i++) {
			// calculate v1 (current row distances) from the previous row v0
			// first element of v1 is A[i+1][0]
			//   edit distance is delete (i+1) chars from s to match empty t
			v1[0] = i + 1;

			// use formula to fill in the rest of the row
			for (int j = 0; j < s2.length(); j++) {
				int cost = 1;
				if (s1.charAt(i) == s2.charAt(j)) {
					cost = 0;
				}
				v1[j + 1] = Math.min(
						v1[j] + 1,              // Cost of insertion
						Math.min(
								v0[j + 1] + 1,  // Cost of remove
								v0[j] + cost)); // Cost of substitution
			}

			// copy v1 (current row) to v0 (previous row) for next iteration
			//System.arraycopy(v1, 0, v0, 0, v0.length);

			// Flip references to current and previous row
			vtemp = v0;
			v0 = v1;
			v1 = vtemp;

		}

		return v0[s2.length()];
	}
}
